# Generated by Django 2.2.6 on 2019-12-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_auto_20191130_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='marca',
            new_name='direccion',
        ),
    ]
