# Generated by Django 2.2.6 on 2019-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_auto_20191202_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
    ]
