# Generated by Django 2.2.6 on 2019-11-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('profesor', 'Es profesor'), ('alumno', 'Es alumno'))},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'permissions': (('profesor', 'Es profesor'), ('alumno', 'Es alumno'))},
        ),
    ]
