# Generated by Django 2.2.3 on 2019-11-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('profesor', 'Es profesor'), ('alumno', 'Es alumno'))},
        ),
    ]
